version: 2
jobs:
  build:
    docker:
        - image: circleci/golang:1.9
    working_directory: /go/src/github.com/zapote/go-ezbus
     
    steps:
      - checkout
      - run:
          name: Install RabbitMQ
          command: |
             docker pull rabbitmq:3-alpine
             docker run -d -p 5762:5762 rabbitmq:3-alpine
      - run: 
          name: Get go deps
          command: go get -v -t -d ./...
      - run:
          name: Unit tests
          command: | 
            go get -u github.com/jstemmer/go-junit-report
            mkdir ~/test-results
            mkdir ~/test-results/junit
            go test ./... -v 2>&1 | go-junit-report > ~/test-results/junit/results.xml
      - store_test_results:
          path: ~/test-results