version: 2
jobs:
  build:
    docker:
        - image: circleci/golang
        - image: circleci/rabbitmq
          ports:
            - "5672:5672"
    working_directory: /go/src/github.com/zapote/go-ezbus
     
    steps:
      - checkout
      
      - run: 
          name: Get go deps
          command: go get -v -t -d ./...
      - run:
          name: Unit tests
          command: | 
            go get -u github.com/jstemmer/go-junit-report
            mkdir ~/test-results
            mkdir ~/test-results/junit
            go test ./... -v 2>&1 | go-junit-report > ~/test-results/junit/results.xml
      - store_test_results:
          path: ~/test-results